Project project_name {
  database_type: 'PostgreSQL'
  Note: 'Description of the project'
}

 Table   buildings   {
    address  varchar(255)  [unique,     not null,note:"to include \"unit\" number"]

  id  integer [  pk,  unique, default:123 ]
                parentId integer
port integer [note:"dsdsds"]

  Note: '''
  This is a block string
  This string can spans over multiple lines.
'''
}

// example

Ref:buildings.id < buildings.parentId

Enum aas {
  n [note: "sds"]
}
