
Project project_name {
  database_type: 'PostgreSQL'
  Note: 'Description of the project'
}

 Table   core.buildings as U   [headercolor: #3498DB] {
    address  varchar(255)  [unique,     not null,note:"to include \"unit\" number"]

  id  "integer" [  pk,  unique, default:123 ]
                parentId integer
port integer [note:"dsdsds"]

  indexes {
    id [pk] // composite primary key
    port
  }


  Note: '''
  This is a block string
  This string can spans over multiple lines.
'''
}

// example

Ref:U.id < U.parentId

Enum aas {
  n [note: "sds"]
}

TableGroup e_commerce {
  core.buildings

  Note: 'xxxxx'
}

Note single_line_note {
  'This is a single line note'
}
